### ISSUE TITLE
Privileges.munki recipe fails

### ISSUE THREAD

**Issue by pnerum** [autopkg/peetinc-recipes#11]
Hi there,

I'm using your Privileges.munki recipe and it seems it's failing with the following error:

`The following recipes failed:
    Privileges.munki
        Error in local.munki.Privileges: Processor: PlistReader: Error: Path '/Users/hradmin/Library/AutoPkg/Cache/local.munki.Privileges/Privileges/Applications/Privileges.app/Contents/Info.plist' doesn't exist!`

I'm not an autopkg expert otherwise I would be able to create a pull request with a fix... I hope you can fix it and it isn't to much work.

All best,

Patrick van Nerum

**Comment by PeetMcK** [comment]
Sorry I missed this checking now.

**Comment by PeetMcK** [comment]
Should be set now. The rewritten recipe pulls the pkg and creates an installs array of the app. I skipped the Voice Over script. I'm super grateful to SAP for creating and maintaining a pkg for this.

**Comment by pnerum** [comment]
Great, thank you! I can confirm it's working again! Have a nice day!
