### ISSUE TITLE
Caffeine recipes 

### ISSUE THREAD

**Issue by patgmac** [autopkg/peetinc-recipes#13]
The GH repo that hosts Caffeine has been abandoned. https://www.caffeine-app.net/ is the new pace for this app. These recipes should either be deprecated or update to use the new source.

**Comment by PeetMcK** [comment]
Thanks Pat. 

Updated.

Let me know if you have issues with the new recipe. Looks like there's a Sparkle feed for it.

**Comment by PeetMcK** [comment]
Thanks Pat.

Updated.

Let me know if you have issues with the new recipe. Looks like there's a Sparkle feed for it, so as long as that stays healthy ...
