### ISSUE TITLE
Kerio Connect Client 10

### ISSUE THREAD

**Issue by precursorca** [autopkg/peetinc-recipes#8]
In the Kerio Connect Client download recipe the Team identifier should be updated to ESPPW8V28N for new GFI v.10 version of app.

<string>identifier "com.Kerio-Connect" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "7WC9K73933"</string>
           

Should now be:

<string>identifier "com.Kerio-Connect" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "ESPPW8V28N"</string>

**Comment by PeetMcK** [comment]
Sorry for missing this. Github's comments mangled the identifier, but it should be updated in the recipe now.

**Comment by PeetMcK** [comment]
https://github.com/autopkg/peetinc-recipes/commit/b18d2f28c7dd49f422ffe2bcd6ecbacdafa833b7
